In [34]:
# import libraries
import numpy as np
import math
import matplotlib.pyplot as plt

In [35]:
# Pad image with zeros
def pad(image,filter):
    r,c = filter.shape
    factor = int(np.floor(r/2))

    r_img, c_img = image.shape
    pad = np.zeros([r_img,factor])
    image = np.hstack([pad,image,pad])

    r_img, c_img = image.shape
    pad = np.zeros([factor,c_img])
    image = np.vstack([pad,image,pad])

    return image

# Norm CC feature matching
def norm_cross_corr(image,filter):
    r,c = image.shape
    ncc = np.zeros([r,c])
    
    padded = pad(image,filter)

    for i in range(r):
        for j in range(c):
            f = padded[i:i+filter.shape[0],j:j+filter.shape[1]]
            len_f = np.sqrt(np.sum(f**2))
            if len_f==0:
                norm_f = np.zeros(f.shape)
            else:
                norm_f = f/len_f
            norm_g = filter/np.sqrt(np.sum(filter**2))

            if filter.size != norm_f.size:
                print('Norm F:', norm_f)
                print('Filter:',filter)
            
            norm_f = np.reshape(norm_f,[1,filter.size])
            norm_g = np.reshape(norm_g,[filter.size,1])
            ncc[i,j] = np.dot(norm_f,norm_g)
            
    return ncc

In [36]:
f = np.array([[0,0,0,0,0,0,0,0],
              [0,2,4,2,0,0,0,0],
              [0,2,0,0,0,0,0,0],
              [0,0,2,0,0,0,2,0],
              [0,0,0,0,0,0,2,0],
              [1,2,1,0,0,2,4,2],
              [0,1,0,0,0,0,0,0],
              [0,1,0,0,0,0,0,0]])

g = np.array([[1,2,1],
              [0,1,0],
              [0,1,0]])

In [37]:
cc = norm_cross_corr(f,g)
print(np.around(cc,3))

[[0.    0.158 0.289 0.158 0.    0.    0.    0.   ]
 [0.    0.289 0.267 0.158 0.    0.    0.    0.   ]
 [0.25  0.668 0.875 0.577 0.354 0.    0.354 0.   ]
 [0.354 0.5   0.5   0.    0.    0.    0.5   0.   ]
 [0.158 0.447 0.589 0.316 0.    0.267 0.625 0.267]
 [0.144 0.401 0.144 0.    0.    0.289 0.535 0.289]
 [0.535 1.    0.535 0.354 0.354 0.632 0.866 0.632]
 [0.25  0.75  0.25  0.    0.    0.    0.    0.   ]]
